---
title: "R Notebook"
output: 
  html_notebook: 
    fig_height: 7
    fig_width: 7
    smart: no
    toc: yes
---

```{r}
# データ読み込み ファイル名指定
f <-
  read.table(
    'data-sakata-10d-30y.csv',
    sep = ",",
    skip = 1,
    header = F,
    fileEncoding = "Shift_JIS",
    stringsAsFactors = F,
    # 空白を削除する
    na.strings=c("", "NULL")
  )

# # 空行削除
is_blank <- function(x){
  is.na(x) | x == ""
}
# すべてが空欄である行を探す
unnecessary_row <- apply(f, 1, function(x){
  all(is_blank(x))
})
# 「すべてが空欄である行」以外を残す（＝空行の除去）
f <- f[!unnecessary_row,]

# 1:月・日 2:旬・半旬
dataType <- ""
if(f[1,1]=="集計開始" && f[1,2]=="集計終了" && is_blank(f[3,1]) && is_blank(f[3,2])){
  dataType <- "旬・半旬"
} else if(is_blank(f[1,1]) && is_blank(f[3,1])) {
  if(f[2,1] == "年月"){
    dataType <- "月"
  } else if(f[2,1] == "年月日"){
    dataType <- "日"
  }
}
dataType

notStartEnd <- function(x){
  result <- sapply(x, function(x){return(x != "集計開始" && x != "集計終了" && x != "年月日")})
  return(result)
}
# str(f)
placeWithNull <- unique(as.vector(as.matrix(f[1,])[1,]))
testPlace <- !is.na(placeWithNull) & notStartEnd(placeWithNull)
placeList <- placeWithNull[!is.na(placeWithNull) & notStartEnd(placeWithNull)]
placeList

dfList <- list()
changeToDate <- function(df){
  # 「年/月」を，その月の1日の日付型に。
  df <- as.Date(paste(as.character(df), "/1", sep = ""))
  return(as.data.frame(df))
}
# 1行目_2行目
removeCharFromTitle1 <- function(string) {
  return(gsub("(\\(.+\\))|(の.+)", "", string))
}
attachTitle <- function(string) {
  replacedTitleVec <- c("qlty", "unfm", "exst")
  names(replacedTitleVec) <- c("品質情報", "均質番号", "現象なし情報")
  return(replacedTitleVec[string])
}
makeColumnName <- function(dfCol) {
  if (is.na(dfCol[3])) {
    retCol = "data"
  } else {
    retCol = attachTitle(dfCol[3])
  }
  return(retCol)
}
# タイトルに設定
setCombinedColumn <- function(df){
  colnames(df) <- apply(df, 2, makeColumnName)
  return(df)
}

# year,month 付け加える
ymLabel <- function(x, formatString) {
  return(format(x, formatString))
}

for(i in placeList){
  # 先頭列は日付
  yearMonthDf <- f[,1]
  yearMonthDf <- changeToDate(yearMonthDf[c(-1:-3)])
  colnames(yearMonthDf) <- "date"
  yearMonthDf$year <- as.factor(ymLabel(yearMonthDf$date, "%Y"))
  yearMonthDf$month <- as.factor(ymLabel(yearMonthDf$date, "%m"))
  # 旬・半旬別の場合は
  placeDf <- f[,which(f[1,] == i)]
  itemWithNull <- unique(as.vector(as.matrix(f[2,])[1,]))
  placeDfList <- list()
  for(j in itemWithNull){
    thisItemDf <- placeDf[,which(placeDf[2,] == j)]
    colnames(thisItemDf) <- apply(thisItemDf, 2, makeColumnName)
    thisItemDf <- thisItemDf[c(-1:-3),]
    placeDfList[[removeCharFromTitle1(j)]] <- cbind(yearMonthDf,thisItemDf)
  }
  dfList[[i]] <- placeDfList
}

typeChange <- function(x){
  # data はnumeric
  replaceColumnToNumeric <- c("data")
  # 以下は factor
  replaceColumnToFactor <- c("qlty", "unfm", "exst")
  columnNames <- names(x)
  # 列名の中で，これに含まれる列はこれこれにする
  for (i in replaceColumnToNumeric) {
    if (any(columnNames == i)) {
      x[,i] <- as.numeric(x[,i])
    }
  }
  for (i in replaceColumnToFactor) {
    if (any(columnNames == i)) {
      x[,i] <- as.factor(x[,i])
    }
  }
  return(x)
}
hierarchyFunc <- function(x){
  y <- lapply(x,typeChange)
  return(y)
}

dfList <- lapply(dfList, hierarchyFunc)
placeList <- names(dfList)
placeList
names(dfList[1])
names(dfList[[1]])

nameList <- list()
getItemList <- function(lst){
  return(lapply(lst,function(x){return(names(x))}))
}
# itemList <- lapply(dfList, getItemList)
getItemList(dfList)



```


```{r fig.height=7, fig.width=7}
# プロット
# dfPlot1 <- dfList[["酒田"]][["平均気温"]]
# dfPlot1_1 <- dfPlot1[dfPlot1$year == 2017,]
# 今年のデータ。
# dfPlot1_2 <- dfPlot1[dfPlot1$year == 2018,]

# 列 data がnumだと箱ひげ
# plot(dfPlot1$month, dfPlot1$data)

# 列 data がcharacterだと散布図
# 全データ散布図
# plot(dfPlot1$month, as.character(dfPlot1$data), pch=15, col="#00ff0090")
# 特定の年のデータ，折れ線で
# plot(dfPlot2$month, as.character(dfPlot2$data), type="o", pch=1, col="#ff000090")

# 月別
# dfPlot2 <- dfList[["酒田"]][["日最低気温"]]
# dfPlot2_2 <- dfPlot2[dfPlot2$year == 2018,]
# dfPlot3 <- dfList[["飛島"]][["日最低気温"]]
# dfPlot3_2 <- dfPlot3[dfPlot3$year == 2018,]

# 旬・半旬 別
dfPlot2 <- dfList[["酒田"]][["日最高気温"]]
dfPlot2_2 <- dfPlot2[dfPlot2$year == 2018,]
dfPlot3 <- dfList[["酒田"]][["日最低気温"]]
dfPlot3_2 <- dfPlot3[dfPlot3$year == 2018,]

# 日別
# dfPlot2 <- dfList[["酒田"]][["最高気温"]]
# dfPlot3 <- dfList[["飛島"]][["最高気温"]]

max(dfPlot2$data, na.rm = T)
# max(dfPlot3$data, na.rm = T)

pchTypes <- c(3,1)
lineCols <- c("red", "blue")
lineTypes <- 3

xlimVec <- c(1,length(dfPlot3$date))
# yMax <- max(max(dfPlot2$data, na.rm = T),max(dfPlot3$data, na.rm = T))
# yMin <- min(min(dfPlot2$data, na.rm = T),min(dfPlot3$data, na.rm = T),0)

yMax <- max(dfPlot2$data, na.rm = T)
yMin <- min(dfPlot3$data, na.rm = T)


```

```{r fig.height=7, fig.width=7}

# quartz("test %d",10,10)

# ラベルはヒラギノ角ゴシW3，枠はL字形
par(family = "HiraKakuPro-W3", bty = "l")
# まず軸だけ描画
plot(0, 0, xlim=xlimVec, ylim=c(yMin,yMax), xaxp=c(1,12,11), panel.first=grid(), xlab="月", ylab="最高気温", main="")
par(new=T)

# boxplot(dfPlot2$data ~ dfPlot2$month, axes=F, ann=F, xlim=xlimVec, ylim=c(yMin,yMax), notch=T, boxwex=0.4, at=(1:12)+0.2, border="#0000ff66", col="#0000ff30")
# par(new=T)
# boxplot(dfPlot3$data ~ dfPlot3$month, axes=F, ann=F, xlim=xlimVec, ylim=c(yMin,yMax), notch=T, boxwex=0.4, at=(1:12)-0.2, border="#ff000066", col="#ff000030")

boxplot(dfPlot2$data ~ dfPlot2$date, axes=F, ann=F, xlim=xlimVec, ylim=c(yMin,yMax), notch=T, boxwex=0.1, at=(1:length(dfPlot2$date))+0.2, border="#0000ff66", col="#0000ff30")
# par(new=T)
# boxplot(dfPlot3$data ~ dfPlot3$date, axes=F, ann=F, xlim=xlimVec, ylim=c(yMin,yMax), notch=T, boxwex=0.1, at=(1:length(dfPlot3$date))-0.2, border="#ff000066", col="#ff000030")

#  axes=F, ann=F で軸とラベル消す
# plot(dfPlot3$month, dfPlot3$data, xlim=xlimVec, ylim=c(yMin,yMax), border="#0000ff66", col="#0000ff30", axes=F, ann=F)
# points(dfPlot1$month, as.character(dfPlot1$data), pch=15, col="#00ff0060")
# points(dfPlot1_1$month, as.character(dfPlot1_1$data), type="b", pch=pchTypes[1], col=lineCols[1], lty=lineTypes)

# 月・旬・半旬
# points(dfPlot2_2$month, as.character(dfPlot2_2$data), type="b", pch=pchTypes[1], col=lineCols[1], lty=lineTypes)
# points(dfPlot3_2$month, as.character(dfPlot3_2$data), type="b", pch=pchTypes[2], col=lineCols[2], lty=lineTypes)

points(dfPlot2_2$date, as.character(dfPlot2_2$data), type="b", pch=pchTypes[1], col=lineCols[1], lty=lineTypes)
points(dfPlot3_2$date, as.character(dfPlot3_2$data), type="b", pch=pchTypes[2], col=lineCols[2], lty=lineTypes)

par(xpd=T)
legend("topleft",c("酒田2018","飛島2018"), pch=pchTypes, col=lineCols, lty=lineTypes, bty="n")


```

テスト
```{r fig.height=10, fig.width=10}
xlimVec <- c(1,36)
junLabels <- seq(2,35,by=3)
junLabelsString <- 1:12
par(family = "HiraKakuPro-W3", bty = "l")
# まず軸だけ描画 x軸は次にaxisで描くので，ここでは描かない
plot(0, 0, xlim=xlimVec, ylim=c(yMin,yMax), xlab="月", ylab="気温", main="", xaxt="n")
axis(side=1, at=junLabels, labels=junLabelsString)
# plot(0, 0, xlim=xlimVec, ylim=c(yMin,yMax), xaxp=c(1,36,35), panel.first=grid(), xlab="月", ylab="最高気温", main="")
par(new=T)
# 
boxplot(dfPlot2$data ~ format(dfPlot2$date, "%m/%d~"), xlim=xlimVec, ylim=c(yMin,yMax), axes=F, ann=F, ylim=c(yMin,yMax), notch=T, boxwex=0.8, border="#ff000066", col="#ff000030")
# 
par(new=T)
boxplot(dfPlot3$data ~ format(dfPlot3$date, "%m/%d~"), xlim=xlimVec, ylim=c(yMin,yMax), axes=F, ann=F, ylim=c(yMin,yMax), notch=T, boxwex=0.8, border="#0000ff66", col="#0000ff30")
par(new=T)
# format(dfPlot2_2$date, "%m/%d~")
# as.character(dfPlot2_2$data)
# plot(dfPlot2_2$date, dfPlot2_2$data, xlim=c(1,3), ylim=c(yMin,yMax), type="b", pch=pchTypes[1], col=lineCols[1], lty=lineTypes)

# 
jun2number <- function(junAsDate){
  as.numeric(format(junAsDate, "%m"))*3-2+(as.numeric(format(junAsDate, "%d"))-1)/10
}
par(new=T)

plot(jun2number(dfPlot2_2$date), dfPlot2_2$data, axes=F, ann=F, xlim=xlimVec, ylim=c(yMin,yMax), type="b", pch=pchTypes[2], col=lineCols[1], lty=lineTypes)
par(new=T)
plot(jun2number(dfPlot3_2$date), dfPlot3_2$data, axes=F, ann=F, xlim=xlimVec, ylim=c(yMin,yMax), type="b", pch=pchTypes[2], col=lineCols[2], lty=lineTypes)
abline(h=c(0,10,20,30), v=(1:12)*3-2.5, col="gray", lty=3)
```


酒田と飛島の，最高気温の差
```{r}
refDate <- dfPlot3["date"]
if(dfPlot2["date"] == refDate){
  differ <- dfPlot3["data"] - dfPlot2["data"]
  names(differ) <- c("result")
}
dfList2 <- data.frame(dfPlot2, differ)

dfList2
```

```{r}
plot(0, 0, xlim=xlimVec, ylim=c(min(dfList2$result, na.rm=T),max(dfList2$result, na.rm=T)), xaxp=c(1,12,11), panel.first=grid(), xlab="月", ylab="最高気温", main="")
abline(h=0, col="gray", lty=2)
par(new=T)
boxplot(dfList2$result ~ dfList2$month, notch=T, xlim=xlimVec, boxwex=1, axes=F, ann=F, border=rgb(0,0,1,0.5), col=rgb(0,0,1,0.2))

```

年を追っての変化
```{r}
# 日・旬・半旬
dfPlot10 <- dfList[["酒田"]][["最低気温"]]
dfPlot11 <- dfList[["酒田"]][["最高気温"]]
# 月
# dfPlot10 <- dfList[["酒田"]][["日最低気温"]]
# dfPlot11 <- dfList[["酒田"]][["日最高気温"]]

dfPlot10_c <- tapply(dfPlot10$data,factor(dfPlot10$year), min)
dfPlot11_h <- tapply(dfPlot11$data,dfPlot11$year, max)
dfPlot10_c
plot(dfPlot10_c)
plot(dfPlot11_h)
```



```{r}
head(dfPlot2,20)
```

```{r eval=FALSE, include=FALSE}
plot.default(jitter(as.numeric(as.character(dfPlot1$month))), as.character(dfPlot1$data), pch=15, col="#00ff0060")

```

```{r}
dfPlot2[dfPlot2$data > 20,]
```

旬別
```{r eval=FALSE, include=FALSE}
# データ読み込み ファイル名指定
f <-
  read.table(
    'data_10.csv',
    sep = ",",
    skip = 1,
    header = F,
    fileEncoding = "Shift_JIS",
    stringsAsFactors = F,
    # 空白を削除する
    na.strings=c("", "NULL")
  )

# # 空行削除
is_blank <- function(x){
  is.na(x) | x == ""
}
# すべてが空欄である行を探す
unnecessary_row <- apply(f, 1, function(x){
  all(is_blank(x))
})
# 「すべてが空欄である行」以外を残す（＝空行の除去）
f <- f[!unnecessary_row,]


# str(f)
placeWithNull <- unique(as.vector(as.matrix(f[1,])[1,]))
placeList <- placeWithNull[!is.na(placeWithNull)]
# placeList

dfList <- list()
changeToDate <- function(df){
  # 「年/月」を，その月の1日の日付型に。
  df <- as.Date(paste(as.character(df), "/1", sep = ""))
  return(as.data.frame(df))
}
# 1行目_2行目
removeCharFromTitle1 <- function(string) {
  return(gsub("(\\(.+\\))|(の.+)", "", string))
}
attachTitle <- function(string) {
  replacedTitleVec <- c("qlty", "unfm", "exst")
  names(replacedTitleVec) <- c("品質情報", "均質番号", "現象なし情報")
  return(replacedTitleVec[string])
}
makeColumnName <- function(dfCol) {
  if (is.na(dfCol[3])) {
    retCol = "data"
  } else {
    retCol = attachTitle(dfCol[3])
  }
  return(retCol)
}
# タイトルに設定
setCombinedColumn <- function(df){
  colnames(df) <- apply(df, 2, makeColumnName)
  return(df)
}

# year,month 付け加える
ymLabel <- function(x, formatString) {
  return(format(x, formatString))
}

for(i in placeList){
  # 先頭列は日付
  yearMonthDf <- f[,1]
# 日付データ部分を，その月の1日のDate型にする
  yearMonthDf <- changeToDate(yearMonthDf[c(-1:-3)])
  # 列名は"date"
  colnames(yearMonthDf) <- "date"
  # 年と月を year,monthという列として付け加える
  yearMonthDf$year <- as.factor(ymLabel(yearMonthDf$date, "%Y"))
  yearMonthDf$month <- as.factor(ymLabel(yearMonthDf$date, "%m"))
  # 地点の行を
  placeDf <- f[,which(f[1,] == i)]
  itemWithNull <- unique(as.vector(as.matrix(f[2,])[1,]))
  placeDfList <- list()
  for(j in itemWithNull){
    thisItemDf <- placeDf[,which(placeDf[2,] == j)]
    colnames(thisItemDf) <- apply(thisItemDf, 2, makeColumnName)
    thisItemDf <- thisItemDf[c(-1:-3),]
    placeDfList[[removeCharFromTitle1(j)]] <- cbind(yearMonthDf,thisItemDf)
  }
  dfList[[i]] <- placeDfList
}

typeChange <- function(x){
  # data はnumeric
  replaceColumnToNumeric <- c("data")
  # 以下は factor
  replaceColumnToFactor <- c("qlty", "unfm", "exst")
  columnNames <- names(x)
  # 列名の中で，これに含まれる列はこれこれにする
  for (i in replaceColumnToNumeric) {
    if (any(columnNames == i)) {
      x[,i] <- as.numeric(x[,i])
    }
  }
  for (i in replaceColumnToFactor) {
    if (any(columnNames == i)) {
      x[,i] <- as.factor(x[,i])
    }
  }
  return(x)
}
hierarchyFunc <- function(x){
  y <- lapply(x,typeChange)
  return(y)
}

dfList <- lapply(dfList, hierarchyFunc)



```
