---
title: "酒田・飛島 旬別年間気温変動"
output: html_notebook
---

```{r}
library("tidyverse")
library("magrittr")

```

```{r}
data_folder <- 'jun-compare_date-separate'
read_jma <- function(csv_f) {
  f <-
    read_csv(
      csv_f
      , col_names = FALSE
      , skip = 1
      , locale = locale(encoding = "cp932")
    )
  # 空行削除
  return(f %>% filter(rowSums(is.na(.)) != ncol(.)))
}

data_files <- list.files(data_folder, full.names = T, pattern = '.csv')
moddata_list <- data_files %>% lapply(read_jma)
moddata_list
```

```{r}
# >>  2. ヘッダ header >>func>
# >>func
# ヘッダとして扱うのは何行目までか
# 先頭から"NA"が続く最後の行までが項目名。その後のちゃんと数字が始まる（NA じゃない）行からがデータ。
# ヘッダの行の最後は，as.numeric が NA 「ではない」（つまり数字）一番始めの（つまりデータの始まる）行の一つ前まで
header_row_end <- function(tbl) {
  result <- (tbl[,1] %>% purrr::map(as.numeric) %>% map({~ !is.na(.)}) %>% flatten_lgl %>% which %>% min)-1
  return(result)
}

# >>  3. 年月日 ymd >>decl>>
ymd_col_names = c("集計開始", "集計終了")
# >>func
# 年月日を表す列はどこまでか
# 先頭で宣言した ymd_col_names や NA「以外」（つまり地名）かどうか
not_ymd_col <- function(x, col_names) {
  result <- !(x %in% col_names) && !is.na(x)
  return(result)
}
# 年月日の列の最後は，地名が始まる一番最初の列(not_ymd_col が TRUE になる最初の列)の，1つ前
ymd_col_end <- function(tbl, col_names) {
  (sapply(tbl[1,], not_ymd_col, col_names) %>% which %>% min) -1
}


# >>func

# >>  4. 年月日のヘッダから列名 >>decl>>
# >>decl
# 1行目が「集計開始」=> start,「集計終了」=> end
start_end_vec <- c("集計開始" = "start", "集計終了" = "end")
# 2行目「年」=> y,「月」=> m,「日」=> d
ymd_vec <- c("年" = "y", "月" = "m", "日" = "d")

# >>  4. 年月日のヘッダから列名 >>func>>
# >>func
# ヘッダは hd_num 行まで
header_rows <- function(tbl, hd_num) {
  return(tbl %>% slice(c(1:hd_num)))
}
# それ以降，つまりデータの行
data_rows <- function(tbl, row_num) {
  return(tbl %>% slice(-c(1:row_num)))
}
# ymdの列
ymd_cols <- function(tbl, col_num) {
  return(tbl %>% dplyr::select(c(1:col_num)))
}
# それ以外の気象データの列
clm_cols <- function(tbl, col_num) {
  return(tbl %>% dplyr::select(-c(1:col_num)))
}

# 変換後，くっつけて列名に
make_ymd_rowname <- function(dt, vec1, vec2) {
  result1 <- vec1[dt[1]]
  result2 <- vec2[dt[2]]
  result <- paste(result1, result2, sep="_")
  return(result)
}


# >>  5. 気象のヘッダから列名 >>func>>
# >>func
# 2行目の「(時間)」「(℃)」「(mm)」「の平均」「の合計」削除
rmv_str_1 <- function(str) {
  result <- str %>% sub("の.+", "", .) %>% sub("\\(.+", "", .)
  return(result)
}
# 3行目の「番号」「情報」削除
rmv_str_2 <- function(str) {
  result <- str %>% sub("情報", "", .) %>% sub("番号", "", .)
  return(result)
}
# 削除した2・3行目"くっつけて列名に
make_clm_rowname <- function(dt) {
  result1 <- rmv_str_1(dt[2])
  result2 <- rmv_str_2(dt[3])
  result_vec <- c(result1, result2)
  # result_vec から，NAではない要素を，"_"で連結して返す
  result <- paste(result_vec[!is.na(result_vec)], collapse="_")
  return(result)
}


```

```{r}
format_jun <- function(data_tbl){
  # >> 2. ヘッダ header 最終行 >>proc>>
  # >>proc
  headers_end <- data_tbl %>% header_row_end

    # >> 3. 年月日 ymd 最終列 >>proc>>
  # >>proc
  ymd_end <- data_tbl %>% ymd_col_end(ymd_col_names)

  # >> 4. 年月日のヘッダから列名 >>proc>>
  # >>proc
  # 年月日のヘッダ
  ymd_headers_tbl <- data_tbl %>% ymd_cols(ymd_end) %>% header_rows(headers_end)

  # 1行目「集計開始」「集計終了」が入ってない列を穴埋め
  # 一度転置してから下方向に補完して，元に戻す
  ymd_headers_tbl[1,] %<>% t %>% as.data.frame() %>% tidyr::fill(1) %>% t
  # 1・2行目変換後，くっつけて列名に
  ymd_col_name <- apply(ymd_headers_tbl, 2, make_ymd_rowname, start_end_vec, ymd_vec)

  # >> 5. 気象のヘッダから列名 >>proc>>
  # >>proc
  # 気象のヘッダ
  clm_headers_tbl <- data_tbl %>% clm_cols(ymd_end) %>% header_rows(headers_end)
  # 削除した2・3行目"くっつけて列名に
  clm_col_name <- apply(clm_headers_tbl, 2, make_clm_rowname)

  # >> 6. 1行目をベクトルに >>proc>>
  # >>proc
  place_row <- data_tbl %>% slice(1)
  place_row_vec <- place_row %>% as.matrix() %>% as.vector()
  # 気象データの列から地名
  placeList <- place_row %>% clm_cols(ymd_end) %>% as.matrix() %>% as.vector() %>% unique

  # >> 7. 最終的なデータを組み立てる >>proc>>
  # >>proc
  # 年月日の列名と("place"と)気象の列名つなげて，データに列名つける
  # データのヘッダ部分削除。地名の列 place 作る。開始年・月・日から日付の列 date 作る。date，年月日，地名，データの順に並べる
  # named_tbl <- data_tbl %>% data_rows(headers_end) %>% mutate(place = placeList[1]) %>% mutate(date = as.Date(str_c(.$X1,.$X2,.$X3, sep='/'))) %>% dplyr::select(date, c(1:ymd_end), place, which(grepl(placeList[1], place_row_vec)))

  # データのヘッダ部分削除
  databody_tbl <- data_tbl %>% data_rows(headers_end)

  # 年月日の部分 + 開始年・月・日から日付の列 st_date
  ymd_tbl <- databody_tbl %>% ymd_cols(ymd_end) %>% mutate_all(as.factor)
  ymd_tbl %<>% mutate(st_date = as.Date(str_c(.$X1,.$X2,.$X3, sep='/')))
  names(ymd_tbl) <- c(ymd_col_name,'st_date')
  # データヘッダ用
  data_colm_name_vec <- c(1:ymd_end, clm_col_name)


  # 地点ごとにデータまとめる
  place_data_list <- placeList %>% lapply(seperate_place_data, databody_tbl, place_row_vec, data_colm_name_vec)
  # 年月日の後に地点毎のデータくっつけて，最後に全地点のデータ一つにまとめる
  result <- place_data_list %>% lapply(cbind_r, ymd_tbl) %>% bind_rows()
  return(result)
}

# ある地点のデータ。地点のベクトル，データ，各列の地点名のベクトル，各列の列名ベクトル。 データからその地点のもの取り出し，列名付けて地名の列つけて返す。
seperate_place_data <- function(this_place, tbl, sel_plc_frm_here_vec, colm_name_vec){
  point_clm_tbl <- tbl %>% dplyr::select(which(grepl(this_place, sel_plc_frm_here_vec)))
  names(point_clm_tbl) <- c(colm_name_vec[which(grepl(this_place, sel_plc_frm_here_vec))])

  point_clm_tbl %<>% mutate(place = this_place)
  return(point_clm_tbl)
}

# 数値の列は，_ が無くて place でも無い列
with_underbar_col <- function(colnames_vec) {
  sapply(colnames_vec, function(x){str_detect(x, "^[^_]+$") && x != 'place'})
}

# 第1引数を後ろ側にくっつける
cbind_r <- function(data1,data2){
  return(cbind(data2,data1))
}

change_colm_type <- function(tbl){
  tbl_colnames_vec <- names(tbl)
  without_underbar_cols <- which(with_underbar_col(tbl_colnames_vec))
  tbl %<>% mutate_at(vars(contains('_')), funs(as.factor)) %>% mutate_at(vars(without_underbar_cols), funs(as.numeric)) %>% mutate(place = as.factor(place)) %>% mutate(st_date = as.Date(st_date))
  return(tbl)
}

```


```{r}
result <- moddata_list %>% lapply(format_jun)
# result <- moddata_list %>% lapply(format_jun) %>% bind_rows()
# ファイルごとにデータがリストで返るので，まとめる
# result
result %<>% bind_rows() %>% change_colm_type()
result
# 6 41 
```

旬
```{r}
result %<>% mutate(jun = paste(start_m,start_d, sep='/')) %>% group_by(place)
x_axis_vec <- c("1/1", "1/11", "1/21", "2/1", "2/11", "2/21", "3/1", "3/11", "3/21", "4/1", "4/11", "4/21", "5/1", "5/11", "5/21", "6/1", "6/11", "6/21", "7/1", "7/11", "7/21", "8/1", "8/11", "8/21", "9/1", "9/11", "9/21", "10/1", "10/11", "10/21", "11/1", "11/11", "11/21", "12/1", "12/11", "12/21")
# x_axis_vec <- as.character(c(11,12, 1:10))
x_axis <- 'jun'
y_axis <- '最低気温'

this_aes <- aes_string(x=x_axis, y=y_axis, group='place', colour='place')
g <- ggplot(data = result)
g <- g + theme_set(theme_bw(base_size = 4,base_family="HiraKakuProN-W3"))
g <- g + geom_point(alpha=0.1, na.rm = TRUE, mapping = aes_string(x=x_axis, y=y_axis, colour='place'))
# g <- g + geom_point(alpha=0.1, na.rm = TRUE, mapping = aes(x=jun, y=平均気温, colour=place))
g <- g + geom_boxplot(alpha=0.5, notch = TRUE, na.rm = TRUE, outlier.size = 0.5, size=0.1, aes_string(x=x_axis, y=y_axis, colour='place'))
# g <- g + geom_boxplot(alpha=0.5, notch = TRUE, na.rm = TRUE, outlier.shape = NA, size=0.1, aes(x=jun, y=平均気温, colour=place))
g <- g + scale_x_discrete(limits = x_axis_vec, labels =x_axis_vec)
g <- g + theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot(g)

quartz(type="pdf", file="saitei.pdf")
plot(g)
dev.off()

# ggplot(data=named_tbl_1, aes(x=start_m, y=降水量, colour='place')) + geom_dotplot(binwidth=1, dotsize=3, binaxis="y", stackdir="center", na.rm = TRUE, fill = 'blue') + geom_boxplot(alpha=0.3, notch = TRUE, na.rm = TRUE, outlier.shape = NA) + scale_fill_brewer(palette="Spectral") + scale_colour_manual(values = qcolours)
# ggplot(data=named_tbl_1, aes(x=start_m, y=降水量)) + geom_boxplot(alpha=0.3, notch = TRUE, na.rm = TRUE, outlier.shape = NA, colour = '#00009966') + scale_fill_brewer(palette="Spectral") + geom_dotplot(binwidth=1, dotsize=3, binaxis="y", stackdir="center", na.rm = TRUE, colour = 'blue', alpha = 0.2)

```

日
```{r}
x_axis <- '最低気温'
filtered_data <- result %>% filter(最低気温 < -5)
filtered_data
this_aes <- aes_string(x=x_axis, group='place', colour='place')
g <- ggplot(data = filtered_data)
g <- g + theme_set(theme_bw(base_size = 4,base_family='HiraKakuProN-W3'))
g <- g + geom_histogram(alpha=0.1, na.rm = TRUE, mapping = this_aes, binwidth=1, position='dodge', size=0.2, origin=-11)
g <- g + facet_grid(place ~ .)
plot(g)

quartz(type='pdf', file='saitei_hist.pdf')
plot(g)
dev.off()

```


```{r}

# >> 最終的なデータを組み立てる >>func>>
# start_m, start_d は 0 padding。
padding_date <- function(str){
  result <- str_sub(str_c('0',str), start = -2, end = -1)
  return(result)
}
named_tbl %<>% mutate(start_m = padding_date(start_m)) %>% mutate(start_d = padding_date(start_d))

# place, (項目名)_hoge を factor に，(項目名)を numeric に。
# 項目名のベクトル
named_colnames_vec <- colnames(named_tbl)
# 数値の列は，_ が無くて place でも無い列

data_col <- function(colnames_vec) {
  sapply(colnames_vec, function(x){str_detect(x, "^[^_]+$") && x != 'place'})
}

without_underbar_cols <- which(data_col(named_colnames_vec))

named_tbl_1 <- named_tbl %>% mutate(place = as.factor(place)) %>% mutate_at(vars(contains('_')), as.factor) %>% mutate_at(vars(without_underbar_cols), funs(as.numeric))


```

